name: "tagged-release"

on:
  push:
    branches:
      - "master"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "windows-latest"

    steps:
    
      - uses: actions/checkout@v2
      - name: "Clone"
        run: Echo "cloning"
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            build/*
